### ISSUE TITLE
https://goo.gl/9qCjMU

### ISSUE THREAD

**Issue by n0bisuke** [n0bisuke/gs7th#4]
kenjiさん質問より。

質問事項：
①Botkitはそもそも使わず、jsをもっとinputしながら公式ドキュメントみながら開発したほうが良いでしょうか。
②Botkitを使っても問題ないのであれば、以下のfbbotkit/bot.jsの中でおかしい部分はどこでしょうか。
③Node + Expressのみで開発していく場合、そもそもBot開発のフローはどんな感じなのか（この質問に関してはざっくりしすぎなので、意図が伝わらなければ無視で問題ないです！）

**Comment by n0bisuke** [comment]
`以下のfbbotkit/bot.jsの中` っていうとどこのことですか?

使わないほうが原因特定がしやすいと思われますので、JSなどの理解が追いついてない場合は素でかいたほうがよさそうです！

**Comment by knj-angler** [comment]
ありがとうございます！Botkit使わない方向で進めます。
